language: go

sudo: required
dist: trusty

go:
- "1.13"
- "1.14"

before_install: true

install: true

before_script:
- cd "${TRAVIS_BUILD_DIR}"

script:
- go test -race -coverprofile=coverage.txt -covermode=atomic ./...

branches:
  only:
  - master
  - develop

notifications:
  email:
    on_success: never
    on_failure: change

after_success:
  - bash <(curl -s https://codecov.io/bash)